<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Traits\ParentSeeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class AppPermissionSeeder extends Seeder
{
    use ParentSeeder;
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table = 'permissions';
        $this->truncateLaratrustTables($table);
        DB::table($table)->insert([
            ['id' => 1, 'parent_id' => null, 'name' => 'none', 'is_parent' => 1, 'display_name' => 'None', 'description' => 'None', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 2, 'parent_id' => null, 'name' => 'accounts_file', 'is_parent' => 1, 'display_name' => 'Accounts File', 'description' => 'Accounts File Upload', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 3, 'parent_id' => 2, 'name' => 'voucher_document_upload', 'is_parent' => null, 'display_name' => 'Voucher Document Upload', 'description' => 'Accounts Voucher Document Upload', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 4, 'parent_id' => 2, 'name' => 'cash_book_document_upload', 'is_parent' => null, 'display_name' => 'Cash Book Document Upload', 'description' => 'Accounts Cash Book Document Upload', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 5, 'parent_id' => null, 'name' => 'voucher_entry', 'is_parent' => 1, 'display_name' => 'Voucher Entry', 'description' => 'Voucher Entry', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 6, 'parent_id' => 5, 'name' => 'voucher_entry_cba', 'is_parent' => null, 'display_name' => 'CBA Voucher Entry', 'description' => 'CBA Voucher Entry', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 7, 'parent_id' => 5, 'name' => 'voucher_entry_journal', 'is_parent' => null, 'display_name' => 'Journal Voucher Entry', 'description' => 'Journal Voucher Entry', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 8, 'parent_id' => 5, 'name' => 'voucher_entry_approve', 'is_parent' => null, 'display_name' => 'Approve Voucher Entry', 'description' => 'Approve Voucher Entry', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 9, 'parent_id' => null, 'name' => 'fixed_assets', 'is_parent' => 1, 'display_name' => 'Fixed Assets', 'description' => 'Fixed Assets', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 10, 'parent_id' => 9, 'name' => 'asset_entry', 'is_parent' => null, 'display_name' => 'Asset Entry', 'description' => 'Asset Entry', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 11, 'parent_id' => 9, 'name' => 'asset_allocation', 'is_parent' => null, 'display_name' => 'Asset Allocation', 'description' => 'Asset Allocation', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 12, 'parent_id' => 9, 'name' => 'asset_depreciation', 'is_parent' => null, 'display_name' => 'Asset Depreciation', 'description' => 'Asset Depreciation', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 13, 'parent_id' => null, 'name' => 'financial_reports', 'is_parent' => 1, 'display_name' => 'Financial Reports', 'description' => 'Financial Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 14, 'parent_id' => 13, 'name' => 'balance_sheet', 'is_parent' => null, 'display_name' => 'Balance Sheet', 'description' => 'Balance Sheet', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 15, 'parent_id' => 13, 'name' => 'profit_and_loss', 'is_parent' => null, 'display_name' => 'Profit and Loss', 'description' => 'Profit and Loss Statement', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 16, 'parent_id' => 13, 'name' => 'cash_flow_statement', 'is_parent' => null, 'display_name' => 'Cash Flow Statement', 'description' => 'Cash Flow Statement', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 17, 'parent_id' => null, 'name' => 'tax_computation', 'is_parent' => 1, 'display_name' => 'Tax Computation', 'description' => 'Tax Computation', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 18, 'parent_id' => 17, 'name' => 'vat_calculation', 'is_parent' => null, 'display_name' => 'VAT Calculation', 'description' => 'VAT Calculation', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 19, 'parent_id' => 17, 'name' => 'tax_return', 'is_parent' => null, 'display_name' => 'Tax Return', 'description' => 'Tax Return Filing', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 20, 'parent_id' => 17, 'name' => 'tax_audit', 'is_parent' => null, 'display_name' => 'Tax Audit', 'description' => 'Tax Audit Process', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 21, 'parent_id' => null, 'name' => 'payroll_management', 'is_parent' => 1, 'display_name' => 'Payroll Management', 'description' => 'Payroll Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 22, 'parent_id' => 21, 'name' => 'salary_processing', 'is_parent' => null, 'display_name' => 'Salary Processing', 'description' => 'Salary Processing', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 23, 'parent_id' => 21, 'name' => 'employee_loans', 'is_parent' => null, 'display_name' => 'Employee Loans', 'description' => 'Employee Loans Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 24, 'parent_id' => 21, 'name' => 'payroll_reports', 'is_parent' => null, 'display_name' => 'Payroll Reports', 'description' => 'Payroll Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 25, 'parent_id' => null, 'name' => 'user_management', 'is_parent' => 1, 'display_name' => 'User Management', 'description' => 'User Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 26, 'parent_id' => 25, 'name' => 'create_user', 'is_parent' => null, 'display_name' => 'Create User', 'description' => 'Create New User', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 27, 'parent_id' => 25, 'name' => 'edit_user', 'is_parent' => null, 'display_name' => 'Edit User', 'description' => 'Edit Existing User', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 28, 'parent_id' => 25, 'name' => 'delete_user', 'is_parent' => null, 'display_name' => 'Delete User', 'description' => 'Delete User', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 29, 'parent_id' => null, 'name' => 'audit_trails', 'is_parent' => 1, 'display_name' => 'Audit Trails', 'description' => 'Audit Trails', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 30, 'parent_id' => 29, 'name' => 'view_audit_trails', 'is_parent' => null, 'display_name' => 'View Audit Trails', 'description' => 'View Audit Trails', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 31, 'parent_id' => 29, 'name' => 'download_audit_trails', 'is_parent' => null, 'display_name' => 'Download Audit Trails', 'description' => 'Download Audit Trails', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 32, 'parent_id' => null, 'name' => 'system_settings', 'is_parent' => 1, 'display_name' => 'System Settings', 'description' => 'System Settings', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 33, 'parent_id' => 32, 'name' => 'update_settings', 'is_parent' => null, 'display_name' => 'Update Settings', 'description' => 'Update System Settings', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 34, 'parent_id' => 32, 'name' => 'backup_database', 'is_parent' => null, 'display_name' => 'Backup Database', 'description' => 'Backup Database', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 35, 'parent_id' => 32, 'name' => 'restore_database', 'is_parent' => null, 'display_name' => 'Restore Database', 'description' => 'Restore Database', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 36, 'parent_id' => null, 'name' => 'financial_year', 'is_parent' => 1, 'display_name' => 'Financial Year', 'description' => 'Financial Year Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 37, 'parent_id' => 36, 'name' => 'open_financial_year', 'is_parent' => null, 'display_name' => 'Open Financial Year', 'description' => 'Open Financial Year', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 38, 'parent_id' => 36, 'name' => 'close_financial_year', 'is_parent' => null, 'display_name' => 'Close Financial Year', 'description' => 'Close Financial Year', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 39, 'parent_id' => null, 'name' => 'document_management', 'is_parent' => 1, 'display_name' => 'Document Management', 'description' => 'Document Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 40, 'parent_id' => 39, 'name' => 'upload_document', 'is_parent' => null, 'display_name' => 'Upload Document', 'description' => 'Upload Document', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 41, 'parent_id' => 39, 'name' => 'download_document', 'is_parent' => null, 'display_name' => 'Download Document', 'description' => 'Download Document', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 42, 'parent_id' => 39, 'name' => 'delete_document', 'is_parent' => null, 'display_name' => 'Delete Document', 'description' => 'Delete Document', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 43, 'parent_id' => null, 'name' => 'project_management', 'is_parent' => 1, 'display_name' => 'Project Management', 'description' => 'Project Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 44, 'parent_id' => 43, 'name' => 'create_project', 'is_parent' => null, 'display_name' => 'Create Project', 'description' => 'Create New Project', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 45, 'parent_id' => 43, 'name' => 'edit_project', 'is_parent' => null, 'display_name' => 'Edit Project', 'description' => 'Edit Existing Project', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 46, 'parent_id' => 43, 'name' => 'delete_project', 'is_parent' => null, 'display_name' => 'Delete Project', 'description' => 'Delete Project', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 47, 'parent_id' => 43, 'name' => 'view_project_reports', 'is_parent' => null, 'display_name' => 'View Project Reports', 'description' => 'View Project Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 48, 'parent_id' => null, 'name' => 'inventory_management', 'is_parent' => 1, 'display_name' => 'Inventory Management', 'description' => 'Inventory Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 49, 'parent_id' => 48, 'name' => 'add_inventory', 'is_parent' => null, 'display_name' => 'Add Inventory', 'description' => 'Add Inventory', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 50, 'parent_id' => 48, 'name' => 'edit_inventory', 'is_parent' => null, 'display_name' => 'Edit Inventory', 'description' => 'Edit Inventory', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 51, 'parent_id' => 48, 'name' => 'delete_inventory', 'is_parent' => null, 'display_name' => 'Delete Inventory', 'description' => 'Delete Inventory', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 52, 'parent_id' => 48, 'name' => 'inventory_reports', 'is_parent' => null, 'display_name' => 'Inventory Reports', 'description' => 'Inventory Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 53, 'parent_id' => null, 'name' => 'budget_management', 'is_parent' => 1, 'display_name' => 'Budget Management', 'description' => 'Budget Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 54, 'parent_id' => 53, 'name' => 'create_budget', 'is_parent' => null, 'display_name' => 'Create Budget', 'description' => 'Create New Budget', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 55, 'parent_id' => 53, 'name' => 'edit_budget', 'is_parent' => null, 'display_name' => 'Edit Budget', 'description' => 'Edit Existing Budget', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 56, 'parent_id' => 53, 'name' => 'approve_budget', 'is_parent' => null, 'display_name' => 'Approve Budget', 'description' => 'Approve Budget', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 57, 'parent_id' => 53, 'name' => 'budget_reports', 'is_parent' => null, 'display_name' => 'Budget Reports', 'description' => 'Budget Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 58, 'parent_id' => null, 'name' => 'report_generation', 'is_parent' => 1, 'display_name' => 'Report Generation', 'description' => 'Report Generation', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 59, 'parent_id' => 58, 'name' => 'generate_financial_reports', 'is_parent' => null, 'display_name' => 'Generate Financial Reports', 'description' => 'Generate Financial Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 60, 'parent_id' => 58, 'name' => 'generate_inventory_reports', 'is_parent' => null, 'display_name' => 'Generate Inventory Reports', 'description' => 'Generate Inventory Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 61, 'parent_id' => 58, 'name' => 'generate_project_reports', 'is_parent' => null, 'display_name' => 'Generate Project Reports', 'description' => 'Generate Project Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 62, 'parent_id' => 58, 'name' => 'generate_user_reports', 'is_parent' => null, 'display_name' => 'Generate User Reports', 'description' => 'Generate User Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 63, 'parent_id' => null, 'name' => 'role_management', 'is_parent' => 1, 'display_name' => 'Role Management', 'description' => 'Role Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 64, 'parent_id' => 63, 'name' => 'create_role', 'is_parent' => null, 'display_name' => 'Create Role', 'description' => 'Create New Role', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 65, 'parent_id' => 63, 'name' => 'edit_role', 'is_parent' => null, 'display_name' => 'Edit Role', 'description' => 'Edit Existing Role', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 66, 'parent_id' => 63, 'name' => 'delete_role', 'is_parent' => null, 'display_name' => 'Delete Role', 'description' => 'Delete Role', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 67, 'parent_id' => 63, 'name' => 'assign_permissions', 'is_parent' => null, 'display_name' => 'Assign Permissions', 'description' => 'Assign Permissions to Role', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 68, 'parent_id' => null, 'name' => 'customer_management', 'is_parent' => 1, 'display_name' => 'Customer Management', 'description' => 'Customer Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 69, 'parent_id' => 68, 'name' => 'add_customer', 'is_parent' => null, 'display_name' => 'Add Customer', 'description' => 'Add New Customer', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 70, 'parent_id' => 68, 'name' => 'edit_customer', 'is_parent' => null, 'display_name' => 'Edit Customer', 'description' => 'Edit Existing Customer', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 71, 'parent_id' => 68, 'name' => 'delete_customer', 'is_parent' => null, 'display_name' => 'Delete Customer', 'description' => 'Delete Customer', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 72, 'parent_id' => 68, 'name' => 'view_customer_reports', 'is_parent' => null, 'display_name' => 'View Customer Reports', 'description' => 'View Customer Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 73, 'parent_id' => null, 'name' => 'supplier_management', 'is_parent' => 1, 'display_name' => 'Supplier Management', 'description' => 'Supplier Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 74, 'parent_id' => 73, 'name' => 'add_supplier', 'is_parent' => null, 'display_name' => 'Add Supplier', 'description' => 'Add New Supplier', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 75, 'parent_id' => 73, 'name' => 'edit_supplier', 'is_parent' => null, 'display_name' => 'Edit Supplier', 'description' => 'Edit Existing Supplier', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 76, 'parent_id' => 73, 'name' => 'delete_supplier', 'is_parent' => null, 'display_name' => 'Delete Supplier', 'description' => 'Delete Supplier', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 77, 'parent_id' => 73, 'name' => 'view_supplier_reports', 'is_parent' => null, 'display_name' => 'View Supplier Reports', 'description' => 'View Supplier Reports', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 78, 'parent_id' => 72, 'name' => 'assign_sales_marketing_users', 'is_parent' => null, 'display_name' => 'Assign Sales Marketing Users', 'description' => 'Assign Sales Marketing Users', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 79, 'parent_id' => 72, 'name' => 'add_user_project_permission', 'is_parent' => null, 'display_name' => 'Add User Project Permission', 'description' => 'Add User Project Permission', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 80, 'parent_id' => null, 'name' => 'fixed_asset_interface',  'is_parent' => 1, 'display_name' => 'Asset Management', 'description' => 'Asset Management', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 81, 'parent_id' => 80, 'name' => 'fixed_asset',  'is_parent' => null, 'display_name' => 'Fixed Asset', 'description' => 'Fixed Asset', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 82, 'parent_id' => 80, 'name' => 'add_fixed_asset',  'is_parent' => null, 'display_name' => 'Add Fixed Asset', 'description' => 'Add Fixed Asset', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 83, 'parent_id' => 80, 'name' => 'add_fixed_asset_specification',  'is_parent' => null, 'display_name' => 'Add Fixed Asset Specification', 'description' => 'Add Fixed Asset Specification', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 84, 'parent_id' => 80, 'name' => 'edit_fixed_asset_specification',  'is_parent' => null, 'display_name' => 'Edit Fixed Asset Specification', 'description' => 'Edit Fixed Asset Specification', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 85, 'parent_id' => 80, 'name' => 'fixed_asset_list',  'is_parent' => null, 'display_name' => 'Fixed Asset List', 'description' => 'Fixed Asset List', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 86, 'parent_id' => 80, 'name' => 'fixed_asset_edit',  'is_parent' => null, 'display_name' => 'Fixed Asset Edit', 'description' => 'Fixed Asset Edit', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 87, 'parent_id' => 80, 'name' => 'fixed_asset_delete',  'is_parent' => null, 'display_name' => 'Fixed Asset Delete', 'description' => 'Fixed Asset Delete', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 88, 'parent_id' => 80, 'name' => 'fixed_asset_distribution',  'is_parent' => null, 'display_name' => 'Fixed Asset Distribution', 'description' => 'Fixed Asset Distribution', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 89, 'parent_id' => 80, 'name' => 'fixed_asset_with_reference_input',  'is_parent' => null, 'display_name' => 'Fixed Asset With Reference Input', 'description' => 'Fixed Asset With Reference Input', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 90, 'parent_id' => 80, 'name' => 'fixed_asset_opening_list',  'is_parent' => null, 'display_name' => 'Fixed Asset Opening List', 'description' => 'Fixed Asset Opening List', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 91, 'parent_id' => 80, 'name' => 'fixed_asset_opening_report',  'is_parent' => null, 'display_name' => 'Fixed Asset Opening Report', 'description' => 'Fixed Asset Opening Report', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 92, 'parent_id' => 80, 'name' => 'fixed_asset_mrf',  'is_parent' => null, 'display_name' => 'Fixed Asset MRF', 'description' => 'Fixed Asset MRF', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 93, 'parent_id' => 80, 'name' => 'fixed_asset_gp',  'is_parent' => null, 'display_name' => 'Fixed Asset GP', 'description' => 'Fixed Asset GP', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 94, 'parent_id' => 80, 'name' => 'fixed_asset_issue',  'is_parent' => null, 'display_name' => 'Fixed Asset Issue', 'description' => 'Fixed Asset Issue', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 95, 'parent_id' => 80, 'name' => 'fixed_asset_damage',  'is_parent' => null, 'display_name' => 'Fixed Asset Damage', 'description' => 'Fixed Asset Damage', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 97, 'parent_id' => 80, 'name' => 'fixed_asset_issue_return',  'is_parent' => null, 'display_name' => 'Fixed Asset Issue Return', 'description' => 'Fixed Asset Issue Return', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 99, 'parent_id' => 80, 'name' => 'delete_fixed_asset_opening_balance',  'is_parent' => null, 'display_name' => 'Delete Fixed Asset Opening Balance', 'description' => 'Delete Fixed Asset Opening Balance', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
            ['id' => 100, 'parent_id' => 80, 'name' => 'edit_fixed_asset_distribution_with_reference',  'is_parent' => null, 'display_name' => 'Edit Fixed Asset Distribution With Reference Balance', 'description' => 'Edit Fixed Asset Distribution With Reference Balance', 'created_at' => date('Y-m-d H:i:s',strtotime(now())), 'updated_at' => date('Y-m-d H:i:s',strtotime(now()))],
        ]);
    }
}



